module.exports = {
  User: require('./User'),
  Student: require('./Student'),
  Trainer: require('./Trainer'),
  Course: require('./Course'),
  Batch: require('./Batch'),
  Campus: require('./Campus'),
  City: require('./City'),
  Slot: require('./Slot'),
  Enrollment: require('./Enrollment'),
  Attendance: require('./Attendance'),
  TrainerAttendance: require('./TrainerAttendance'),
  Payment: require('./Payment'),
  Assignment: require('./Assignment'),
  Submission: require('./Submission'),
  Quiz: require('./Quiz'),
  QuizAttempt: require('./QuizAttempt'),
  Feedback: require('./Feedback'),
  CourseProgress: require('./CourseProgress'),
  Role: require('./Role'),
  Counter: require('./Counter'),
};
